use olist_db;

/*Que1: Calculate the number of orders per month in 2018 */
SELECT 
    MONTHNAME(order_purchase_timestamp) AS month_name, 
    COUNT(distinct order_id) AS total_orders
FROM orders
WHERE YEAR(order_purchase_timestamp) = 2018
GROUP BY month_name
ORDER BY MIN(MONTH(order_purchase_timestamp));

/*Que2: Find the average number of products per order, grouped by customer city*/
SELECT 
    c.customer_city, 
    ROUND(COUNT(oi.product_id) / COUNT(DISTINCT oi.order_id), 2) AS avg_products_per_order
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.customer_city
ORDER BY avg_products_per_order DESC
limit 10;

/*Que3: Calculate the percentage of total revenue contributed by each product category.*/
SELECT 
    p.product_category, 
    ROUND(
        SUM(oi.price) * 100.0 / SUM(SUM(oi.price)) OVER(), 
        1
    ) AS revenue_percentage
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_category
ORDER BY revenue_percentage DESC
LIMIT 10;

/*Que4: Identify the correlation between product price and the number of times a product has been purchased*/
SELECT 
	p.product_id,
    p.product_category,
    AVG(oi.price) AS mean_price, -- Matches 'price': 'mean'
    COUNT(oi.order_id) AS purchase_count -- Matches 'order_id': 'count'
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_category
ORDER BY purchase_count DESC
limit 10;

/*Que5: Calculate the total revenue generated by each seller, and rank them by revenue.*/
SELECT 
    seller_id, 
    SUM(price) AS total_revenue,
    DENSE_RANK() OVER (ORDER BY SUM(price) DESC) AS seller_rank
FROM order_items
GROUP BY seller_id
limit 10;